script: |
  echo "🚀 Starting Deploy"

  cd ${{ secrets.VPS_PATH }}

  echo "📦 Pulling latest code"
  git fetch --all
  git reset --hard origin/main

  echo "🐳 Rebuilding Docker"
  docker compose down
  docker compose up -d --build

  echo "✅ Deploy Finished"
